version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/TranzQL"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/TranzTracker"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/Migrator"
    schedule:
      interval: "daily"
