version: '3'

services: 
  graphql:
    build: ./TranzQL
    restart: always
    volumes: 
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '8080:8080'
    links:
      - mongo
    env_file:
      - ./.env
    environment: 
      - MONGO_HOST=mongo
      - SSL_KEY_PATH=/etc/letsencrypt/live/${HOST_URL}
  mongo:
    image: mongo
    ports:
      - '27017:27017'
      
