version: '3'

services: 
  graphql:
    build: ./TranzQL
    restart: always
    ports:
      - '80:80'
    links:
      - mongo
    volumes:
      - ./TranzQL:/usr/src/app
    environment:
      - NODE_ENV=development
      - TRANZQL_PORT=80
      - MONGO_HOST=mongo
      - MONGO_DB=tranzurban
      - MONGO_GTFS_DB=gtfs
      - AT_API_KEY=dcefb8b705d24f1cbf22dc47599eb69d
  mongo:
    image: mongo
    ports:
      - '27017:27017'
      