version: '3'

services: 
  graphql:
    build: ./TranzQL
    restart: always
    volumes: 
      - ${SSL_KEY_PATH}:/usr/cert
    ports:
      - '80:80'
      - '443:443'
    links:
      - mongo
    env_file:
      - ./.env
    environment: 
      - MONGO_HOST=mongo
      - SSL_KEY_PATH=/usr/cert
  mongo:
    image: mongo
    ports:
      - '27017:27017'
      