version: '3'

services: 
  graphql:
    build: ./TranzQL
    restart: always
    ports:
      - '80:80'
    links:
      - mongo
    env_file:
      - ./.env
  mongo:
    image: mongo
    ports:
      - '27017:27017'
      